# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 667)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.canvas = QtWidgets.QLabel(self.centralwidget)
        self.canvas.setGeometry(QtCore.QRect(10, 10, 600, 600))
        self.canvas.setAutoFillBackground(True)
        self.canvas.setFrameShape(QtWidgets.QFrame.Box)
        self.canvas.setText("")
        self.canvas.setObjectName("canvas")
        self.pb_draw_line = QtWidgets.QPushButton(self.centralwidget)
        self.pb_draw_line.setGeometry(QtCore.QRect(670, 130, 111, 23))
        self.pb_draw_line.setObjectName("pb_draw_line")
        self.le_line_x1 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_line_x1.setGeometry(QtCore.QRect(670, 10, 113, 20))
        self.le_line_x1.setObjectName("le_line_x1")
        self.le_line_y1 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_line_y1.setGeometry(QtCore.QRect(670, 40, 113, 20))
        self.le_line_y1.setObjectName("le_line_y1")
        self.le_circle_r = QtWidgets.QLineEdit(self.centralwidget)
        self.le_circle_r.setGeometry(QtCore.QRect(670, 230, 113, 20))
        self.le_circle_r.setObjectName("le_circle_r")
        self.le_circle_x = QtWidgets.QLineEdit(self.centralwidget)
        self.le_circle_x.setGeometry(QtCore.QRect(670, 170, 113, 20))
        self.le_circle_x.setObjectName("le_circle_x")
        self.le_circle_y = QtWidgets.QLineEdit(self.centralwidget)
        self.le_circle_y.setGeometry(QtCore.QRect(670, 200, 113, 20))
        self.le_circle_y.setObjectName("le_circle_y")
        self.pb_draw_circle = QtWidgets.QPushButton(self.centralwidget)
        self.pb_draw_circle.setGeometry(QtCore.QRect(670, 260, 111, 23))
        self.pb_draw_circle.setObjectName("pb_draw_circle")
        self.le_line_x2 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_line_x2.setGeometry(QtCore.QRect(670, 70, 113, 20))
        self.le_line_x2.setObjectName("le_line_x2")
        self.le_line_y2 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_line_y2.setGeometry(QtCore.QRect(670, 100, 113, 20))
        self.le_line_y2.setObjectName("le_line_y2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(610, 10, 51, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(610, 70, 51, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(610, 40, 51, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(610, 100, 51, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(610, 170, 51, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(610, 200, 51, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(610, 230, 51, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb_draw_line.setText(_translate("MainWindow", "Прямая"))
        self.le_line_x1.setText(_translate("MainWindow", "0"))
        self.le_line_y1.setText(_translate("MainWindow", "0"))
        self.le_circle_r.setText(_translate("MainWindow", "3"))
        self.le_circle_x.setText(_translate("MainWindow", "0"))
        self.le_circle_y.setText(_translate("MainWindow", "0"))
        self.pb_draw_circle.setText(_translate("MainWindow", "Круг"))
        self.le_line_x2.setText(_translate("MainWindow", "5"))
        self.le_line_y2.setText(_translate("MainWindow", "3"))
        self.label.setText(_translate("MainWindow", "x1"))
        self.label_2.setText(_translate("MainWindow", "x2"))
        self.label_3.setText(_translate("MainWindow", "y1"))
        self.label_4.setText(_translate("MainWindow", "y2"))
        self.label_5.setText(_translate("MainWindow", "x"))
        self.label_6.setText(_translate("MainWindow", "y"))
        self.label_7.setText(_translate("MainWindow", "r"))
